"""
Consolidated Test File: test_consolidated_e2e.py

This file was automatically generated by consolidating the following test files:
test_core_use_cases_e2e.py, test_practical_e2e.py
"""

import sys
import os
import unittest
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from packetfuzz.dictionary_manager import DictionaryManager
from packetfuzz.fuzzing_framework import FuzzingCampaign
from scapy.all import IP, TCP

from scapy.all import IP, TCP, Raw

from scapy.all import IP, TCP, UDP, ICMP, Raw

import tempfile
import subprocess
import time
import json
import shutil
from typing import Dict, List, Any, Optional, Tuple

class TestCoreUseCasesEndToEnd(unittest.TestCase):
    """Core use case end-to-end tests with strong pass/fail criteria"""
    
    def setUp(self):
        """Set up test environment"""
        self.temp_dir = tempfile.mkdtemp()
        self.project_root = os.path.dirname(os.path.dirname(__file__))
    
    def tearDown(self):
        """Clean up test environment"""
        shutil.rmtree(self.temp_dir, ignore_errors=True)
    
    def run_cli_command(self, args, timeout=30):
        """Run CLI command and return results"""
        try:
            cmd = [sys.executable, "-m", "packetfuzz"] + args
            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=timeout, cwd=self.project_root
            )
            return result.returncode, result.stdout, result.stderr
        except subprocess.TimeoutExpired:
            return -1, "", "Command timed out"
        except (OSError, subprocess.SubprocessError) as e:
            return -2, "", str(e)
    
    def test_quick_start_example_e2e(self):
        """End-to-end test: Quick start example works as documented"""

        quick_start_path = os.path.join(self.project_root, "examples", "basic", "01_quick_start.py")

        self.assertTrue(os.path.exists(quick_start_path), 
                       f"Quick start example not found: {quick_start_path}")

        start_time = time.time()
        returncode, stdout, stderr = self.run_cli_command([
            quick_start_path,
            "--disable-network",
            "--max-iterations", "10",
            "-v"
        ], timeout=60)
        execution_time = time.time() - start_time

        if returncode == -1:  # Timeout

            combined_output = stdout + stderr
            if len(combined_output) > 100:  # Some output means it started
                self.skipTest("Quick start example timed out - may be due to high iteration count")
        
        self.assertEqual(returncode, 0, f"Quick start failed: {stderr}")

        self.assertLess(execution_time, 60.0, f"Quick start too slow: {execution_time:.1f}s")  # Increased threshold

        combined_output = stdout + stderr
        success_indicators = ["campaign", "packet", "complete", "iteration"]
        found_indicators = sum(1 for indicator in success_indicators 
                             if indicator.lower() in combined_output.lower())
        
        self.assertGreaterEqual(found_indicators, 3,
                              f"Quick start should produce informative output, found {found_indicators}/4 indicators")

        fuzzing_indicators = ["fuzz", "mutation", "send"]
        found_fuzzing = sum(1 for indicator in fuzzing_indicators
                          if indicator.lower() in combined_output.lower())
        
        self.assertGreater(found_fuzzing, 0, "Quick start should show fuzzing activity")
    
    def test_basic_http_fuzzing_workflow_e2e(self):
        """End-to-end test: Basic HTTP fuzzing workflow"""

        campaign_file = os.path.join(self.temp_dir, "http_fuzz_test.py")
        pcap_file = os.path.join(self.temp_dir, "http_fuzz_output.pcap")
        
        campaign_content = f'''#!/usr/bin/env python3

class HTTPFuzzingCampaign(FuzzingCampaign):
    name = "HTTP Fuzzing E2E Test"
    target = "192.168.1.100"
    iterations = 12
    rate_limit = 100.0
    verbose = True
    output_network = False
    output_pcap = "{pcap_file}"
    
    def get_packet(self):
        http_request = b"GET / HTTP/1.1\\r\\nHost: " + self.target.encode() + b"\\r\\n\\r\\n"
        return IP(dst=self.target, ttl=64) / TCP(dport=80, sport=12345) / Raw(load=http_request)
'''

class ErrorRecoveryTestCampaign(FuzzingCampaign):
    name = "Error Recovery Test Campaign"
    target = "192.168.1.100"
    iterations = 8
    rate_limit = 100.0
    verbose = True
    output_network = False
    output_pcap = "{pcap_file}"
    
    def get_packet(self):

        return IP(dst=self.target, ttl=64) / TCP(dport=80, sport=12345, flags="S") / Raw(b"ERROR_TEST_PAYLOAD")
'''

class MultiPacketTestCampaign(FuzzingCampaign):
    name = "Multi Packet Type Test Campaign"
    target = "192.168.1.100"
    iterations = 15
    rate_limit = 100.0
    verbose = True
    output_network = False
    output_pcap = "{pcap_file}"
    
    def __init__(self):
        super().__init__()
        self.packet_count = 0
    
    def get_packet(self):

        packet_type = self.packet_count % 3
        self.packet_count += 1
        
        if packet_type == 0:

            return IP(dst=self.target) / TCP(dport=80, sport=12345) / Raw(b"TCP_TEST")
        elif packet_type == 1:

            return IP(dst=self.target) / UDP(dport=53, sport=12345) / Raw(b"UDP_TEST")
        else:

            return IP(dst=self.target) / ICMP(type=8, code=0) / Raw(b"ICMP_TEST")
'''

class TestPracticalWorkflowsEndToEnd(unittest.TestCase):
    """Practical end-to-end tests focusing on real user workflows"""
    
    def setUp(self):
        """Set up test environment"""
        self.temp_dir = tempfile.mkdtemp()
        self.project_root = os.path.dirname(os.path.dirname(__file__))
    
    def tearDown(self):
        """Clean up test environment"""
        shutil.rmtree(self.temp_dir, ignore_errors=True)
    
    def run_cli_command(self, args: List[str], timeout: int = 30) -> Tuple[int, str, str]:
        """Run a CLI command and return result"""
        try:
            cmd = [sys.executable, "-m", "packetfuzz"] + args
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=self.project_root
            )
            return result.returncode, result.stdout, result.stderr
        except subprocess.TimeoutExpired:
            return -1, "", "Command timed out"
        except (OSError, subprocess.SubprocessError) as e:
            return -2, "", str(e)
    
    def create_basic_campaign_file(self, filename: str, iterations: int = 10) -> str:
        """Create a basic campaign file for testing"""
        campaign_file = os.path.join(self.temp_dir, filename)
        pcap_file = os.path.join(self.temp_dir, f"{filename}_output.pcap")
        
        campaign_content = f'''#!/usr/bin/env python3

class PracticalTestCampaign(FuzzingCampaign):
    name = "Practical E2E Test Campaign"
    target = "192.168.1.100"
    iterations = {iterations}
    rate_limit = 100.0
    verbose = True
    output_network = False
    output_pcap = "{pcap_file}"
    
    def get_packet(self):
        return IP(dst=self.target, ttl=64) / TCP(dport=80, sport=12345) / Raw(b"PRACTICAL_TEST")
'''

class ParameterTestCampaign(FuzzingCampaign):
    name = "Parameter Test Campaign"
    target = "192.168.1.100"

    iterations = 1
    verbose = False
    output_network = False
    output_pcap = "test_output.pcap" # Original was a template: {pcap_file}
    
    def get_packet(self):
        return IP(dst=self.target) / TCP(dport=80) / Raw(b"PARAM_TEST")
'''

class TestFileSystemInteractionEndToEnd(unittest.TestCase):
    """End-to-end tests for file system interactions"""
    
    def setUp(self):
        """Set up test environment"""
        self.temp_dir = tempfile.mkdtemp()
        self.project_root = os.path.dirname(os.path.dirname(__file__))
    
    def tearDown(self):
        """Clean up test environment"""
        shutil.rmtree(self.temp_dir, ignore_errors=True)
    
    def test_pcap_output_locations_e2e(self):
        """End-to-end test: PCAP files are created in correct locations"""

        test_locations = [
            ("relative_path", "test_output.pcap"),
            ("absolute_path", os.path.join(self.temp_dir, "absolute_output.pcap")),
            ("nested_dir", os.path.join(self.temp_dir, "nested", "dir", "nested_output.pcap"))
        ]
        
        location_results = []
        
        for test_name, pcap_path in test_locations:

            campaign_file = os.path.join(self.temp_dir, f"location_test_{test_name}.py")
            
            campaign_content = f'''#!/usr/bin/env python3

class LocationTestCampaign(FuzzingCampaign):
    name = "Location Test Campaign"
    target = "192.168.1.100"
    iterations = 5
    rate_limit = 100.0
    verbose = False
    output_network = False
    output_pcap = "{pcap_path}"
    
    def get_packet(self):
        return IP(dst=self.target) / TCP(dport=80)
'''

class DictTestCampaign(FuzzingCampaign):
    name = "Dictionary Test Campaign"
    target = "192.168.1.100"
    iterations = 5
    rate_limit = 100.0
    verbose = False
    output_network = False
    output_pcap = "{pcap_file}"
    
    def get_packet(self):

        try:
            dict_manager = DictionaryManager()

            return IP(dst=self.target) / TCP(dport=80)
        except ImportError as e:

            return IP(dst=self.target) / TCP(dport=80)
'''
